
spring:
  datasource:
    url: jdbc:mysql://47.118.67.118:3306/gulimall_pms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 500000
  cloud:
    nacos:
      discovery:
        server-addr: 47.118.67.118:8848
    alicloud:
      access-key: LTAI5t5zqz42USkWhz1pw2VM
      secret-key: 0WeFVGgldcY2d69fQnotd172nW7Zur
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
  application:
    name: gulimall-product
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8000
logging:
  level:
    com.situjunjie.gulimall.product: debug
