
spring:
  datasource:
    url: jdbc:mysql://rm-bp10io6z0flrid09vmo.mysql.rds.aliyuncs.com:3306/gulimall_pms
    username: root
    password: Situ20154103
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 500000
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.1:8848
  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  redis:
    host: 192.169.56.10
    port: 6379

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 11010
logging:
  level:
    com.situjunjie.gulimall.product: debug