
spring:
  datasource:
    url: jdbc:mysql://rm-bp10io6z0flrid09vmo.mysql.rds.aliyuncs.com:3306/gulimall_sms
    username: root
    password: Situ20154103
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.118.67.118:8848
  application:
    name: gulimall-coupon
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xmlnet
  global-config:
    db-config:
      id-type: auto
server:
  port: 10086
