spring:
  datasource:
    url: jdbc:mysql://rm-bp10io6z0flrid09vmo.mysql.rds.aliyuncs.com:3306/gulimall_sms
    username: root
    password: Situ20154103
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.1:8848
    sentinel:
      transport:
        dashboard: 192.168.56.1:8080
        port: 8719
  application:
    name: gulimall-coupon
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xmlnet
  global-config:
    db-config:
      id-type: auto
server:
  port: 10086
