spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.1:8848
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
server:
  port: 12289


logging:
  level:
    com.situjunjie.gulimall.gulimallsearch: debug
