spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.118.67.118:8848
  application:
    name: gulimall-search
server:
  port: 11089

logging:
  level:
    com.situjunjie.gulimall.gulimallsearch: debug
