spring:
  application:
    name: gulimall-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 192.168.56.1:8080
        port: 8719
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  redis:
    port: 6379
    host: 192.168.56.10
  session:
    store-type: redis
server:
  port: 13231