spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.10
  session:
    store-type: redis
server:
  port: 30000
gulimall:
  threadpool:
    core-pool-size: 10
    maximum-pool-size: 100
    keep-alive-time: 30