
spring:
  datasource:
    url: jdbc:mysql://rm-bp10io6z0flrid09vmo.mysql.rds.aliyuncs.com:3306/gulimall_wms
    username: root
    password: Situ20154103
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-ware
  cloud:
    nacos:
      discovery:
        server-addr: http://47.118.67.118:8848/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 12000
logging:
  level:
    com.situjunjie: debug

